spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: truststore
              mountPath: /app/truststore
          env:
            - name: JAVA_OPTIONS
              value: >
                -Djavax.net.ssl.trustStore=/app/truststore/enmasse.jks
                -Djavax.net.ssl.trustStorePassword=password
                -Djavax.net.ssl.trustStoreType=JKS
      volumes:
        - secret:
            secretName: enmasse-truststore
          name: truststore